export default function createDeepNestedPaintLayout({ ui, rendererName }) {
    //

    const shell = ui.create()
    shell.setStyle('flex', '1')
    shell.setStyle('flexDirection', 'column')
    shell.setStyle('padding', '24px')
    shell.setStyle('borderTopWidth', '3px')
    shell.setStyle('borderLeftWidth', '3px')
    shell.setStyle('borderRightWidth', '3px')
    shell.setStyle('borderBottomWidth', '3px')
    shell.setStyle('borderTopStyle', 'solid')
    shell.setStyle('borderLeftStyle', 'solid')
    shell.setStyle('borderRightStyle', 'solid')
    shell.setStyle('borderBottomStyle', 'solid')
    shell.setStyle('borderTopColor', '#222')
    shell.setStyle('borderLeftColor', '#222')
    shell.setStyle('borderRightColor', '#222')
    shell.setStyle('borderBottomColor', '#222')
    shell.setStyle('gap', '12px')
    shell.setStyle('backgroundColor', '#f4f4f4')
    ui.root.add(shell)

    const header = ui.create()
    header.setStyle('height', '44px')
    header.setStyle('backgroundColor', '#d8e8ff')
    shell.add(header)

    const row = ui.create()
    row.setStyle('height', '420px')
    row.setStyle('flexDirection', 'row')
    row.setStyle('padding', '13px')
    row.setStyle('borderTopWidth', '2px')
    row.setStyle('borderLeftWidth', '2px')
    row.setStyle('borderRightWidth', '2px')
    row.setStyle('borderBottomWidth', '2px')
    row.setStyle('borderTopStyle', 'solid')
    row.setStyle('borderLeftStyle', 'solid')
    row.setStyle('borderRightStyle', 'solid')
    row.setStyle('borderBottomStyle', 'solid')
    row.setStyle('borderTopColor', '#446')
    row.setStyle('borderLeftColor', '#446')
    row.setStyle('borderRightColor', '#446')
    row.setStyle('borderBottomColor', '#446')
    row.setStyle('gap', '17px')
    row.setStyle('alignItems', 'center')
    row.setStyle('backgroundColor', '#eef5ee')
    shell.add(row)

    const row_child_1 = ui.create()
    row_child_1.setStyle('width', '92px')
    row_child_1.setStyle('height', '146px')
    row_child_1.setStyle('backgroundColor', '#f0d8d8')

    row.add(row_child_1)

    const shiftedColumn = ui.create()
    shiftedColumn.setStyle('flex', '1')
    shiftedColumn.setStyle('height', '320px')
    shiftedColumn.setStyle('position', 'relative')
    shiftedColumn.setStyle('left', '11px')
    shiftedColumn.setStyle('top', '7px')
    shiftedColumn.setStyle('flexDirection', 'column')
    shiftedColumn.setStyle('justifyContent', 'center')
    shiftedColumn.setStyle('alignItems', 'flex-end')
    shiftedColumn.setStyle('padding', '19px')
    shiftedColumn.setStyle('borderTopWidth', '4px')
    shiftedColumn.setStyle('borderLeftWidth', '4px')
    shiftedColumn.setStyle('borderRightWidth', '4px')
    shiftedColumn.setStyle('borderBottomWidth', '4px')
    shiftedColumn.setStyle('borderTopStyle', 'solid')
    shiftedColumn.setStyle('borderLeftStyle', 'solid')
    shiftedColumn.setStyle('borderRightStyle', 'solid')
    shiftedColumn.setStyle('borderBottomStyle', 'solid')
    shiftedColumn.setStyle('borderTopColor', '#484')
    shiftedColumn.setStyle('borderLeftColor', '#484')
    shiftedColumn.setStyle('borderRightColor', '#484')
    shiftedColumn.setStyle('borderBottomColor', '#484')
    shiftedColumn.setStyle('gap', '15px')
    shiftedColumn.setStyle('backgroundColor', '#fff8df')
    row.add(shiftedColumn)

    const shiftedColumn_child_2 = ui.create()
    shiftedColumn_child_2.setStyle('width', '88px')
    shiftedColumn_child_2.setStyle('height', '36px')
    shiftedColumn_child_2.setStyle('backgroundColor', '#dfdfdf')

    shiftedColumn.add(shiftedColumn_child_2)

    const nestedRow = ui.create()
    nestedRow.setStyle('width', '468px')
    nestedRow.setStyle('height', '190px')
    nestedRow.setStyle('position', 'relative')
    nestedRow.setStyle('flexDirection', 'row')
    nestedRow.setStyle('justifyContent', 'space-between')
    nestedRow.setStyle('alignItems', 'center')
    nestedRow.setStyle('padding', '11px')
    nestedRow.setStyle('borderTopWidth', '3px')
    nestedRow.setStyle('borderLeftWidth', '3px')
    nestedRow.setStyle('borderRightWidth', '3px')
    nestedRow.setStyle('borderBottomWidth', '3px')
    nestedRow.setStyle('borderTopStyle', 'solid')
    nestedRow.setStyle('borderLeftStyle', 'solid')
    nestedRow.setStyle('borderRightStyle', 'solid')
    nestedRow.setStyle('borderBottomStyle', 'solid')
    nestedRow.setStyle('borderTopColor', '#884')
    nestedRow.setStyle('borderLeftColor', '#884')
    nestedRow.setStyle('borderRightColor', '#884')
    nestedRow.setStyle('borderBottomColor', '#884')
    nestedRow.setStyle('gap', '9px')
    nestedRow.setStyle('backgroundColor', '#f8eaff')
    shiftedColumn.add(nestedRow)

    const flowStack = ui.create()
    flowStack.setStyle('width', '124px')
    flowStack.setStyle('height', '132px')
    flowStack.setStyle('flexDirection', 'column')
    flowStack.setStyle('justifyContent', 'flex-end')
    flowStack.setStyle('alignItems', 'flex-start')
    flowStack.setStyle('padding', '7px')
    flowStack.setStyle('borderTopWidth', '2px')
    flowStack.setStyle('borderLeftWidth', '2px')
    flowStack.setStyle('borderRightWidth', '2px')
    flowStack.setStyle('borderBottomWidth', '2px')
    flowStack.setStyle('borderTopStyle', 'solid')
    flowStack.setStyle('borderLeftStyle', 'solid')
    flowStack.setStyle('borderRightStyle', 'solid')
    flowStack.setStyle('borderBottomStyle', 'solid')
    flowStack.setStyle('borderTopColor', '#855')
    flowStack.setStyle('borderLeftColor', '#855')
    flowStack.setStyle('borderRightColor', '#855')
    flowStack.setStyle('borderBottomColor', '#855')
    flowStack.setStyle('gap', '6px')
    flowStack.setStyle('backgroundColor', '#ffe8e8')
    nestedRow.add(flowStack)

    const flowStack_child_3 = ui.create()
    flowStack_child_3.setStyle('width', '42px')
    flowStack_child_3.setStyle('height', '28px')
    flowStack_child_3.setStyle('backgroundColor', '#f2caca')

    flowStack.add(flowStack_child_3)

    const flowMarker = ui.create()
    flowMarker.setStyle('width', '20px')
    flowMarker.setStyle('height', '20px')
    flowMarker.setStyle('backgroundColor', '#ff0000')
    flowStack.add(flowMarker)

    const alignedHost = ui.create()
    alignedHost.setStyle('width', '148px')
    alignedHost.setStyle('height', '132px')
    alignedHost.setStyle('flexDirection', 'row')
    alignedHost.setStyle('justifyContent', 'center')
    alignedHost.setStyle('alignItems', 'flex-end')
    alignedHost.setStyle('padding', '8px')
    alignedHost.setStyle('borderTopWidth', '2px')
    alignedHost.setStyle('borderLeftWidth', '2px')
    alignedHost.setStyle('borderRightWidth', '2px')
    alignedHost.setStyle('borderBottomWidth', '2px')
    alignedHost.setStyle('borderTopStyle', 'solid')
    alignedHost.setStyle('borderLeftStyle', 'solid')
    alignedHost.setStyle('borderRightStyle', 'solid')
    alignedHost.setStyle('borderBottomStyle', 'solid')
    alignedHost.setStyle('borderTopColor', '#585')
    alignedHost.setStyle('borderLeftColor', '#585')
    alignedHost.setStyle('borderRightColor', '#585')
    alignedHost.setStyle('borderBottomColor', '#585')
    alignedHost.setStyle('backgroundColor', '#eaffea')
    nestedRow.add(alignedHost)

    const alignedMarker = ui.create()
    alignedMarker.setStyle('width', '24px')
    alignedMarker.setStyle('height', '18px')
    alignedMarker.setStyle('backgroundColor', '#00aa00')
    alignedHost.add(alignedMarker)

    const absoluteHost = ui.create()
    absoluteHost.setStyle('width', '138px')
    absoluteHost.setStyle('height', '132px')
    absoluteHost.setStyle('position', 'relative')
    absoluteHost.setStyle('flexDirection', 'column')
    absoluteHost.setStyle('padding', '10px')
    absoluteHost.setStyle('borderTopWidth', '2px')
    absoluteHost.setStyle('borderLeftWidth', '2px')
    absoluteHost.setStyle('borderRightWidth', '2px')
    absoluteHost.setStyle('borderBottomWidth', '2px')
    absoluteHost.setStyle('borderTopStyle', 'solid')
    absoluteHost.setStyle('borderLeftStyle', 'solid')
    absoluteHost.setStyle('borderRightStyle', 'solid')
    absoluteHost.setStyle('borderBottomStyle', 'solid')
    absoluteHost.setStyle('borderTopColor', '#558')
    absoluteHost.setStyle('borderLeftColor', '#558')
    absoluteHost.setStyle('borderRightColor', '#558')
    absoluteHost.setStyle('borderBottomColor', '#558')
    absoluteHost.setStyle('backgroundColor', '#e8eaff')
    nestedRow.add(absoluteHost)

    const absoluteHost_child_4 = ui.create()
    absoluteHost_child_4.setStyle('width', '52px')
    absoluteHost_child_4.setStyle('height', '34px')
    absoluteHost_child_4.setStyle('backgroundColor', '#cacaf2')

    absoluteHost.add(absoluteHost_child_4)

    const absoluteMarker = ui.create()
    absoluteMarker.setStyle('width', '22px')
    absoluteMarker.setStyle('height', '22px')
    absoluteMarker.setStyle('position', 'absolute')
    absoluteMarker.setStyle('right', '13px')
    absoluteMarker.setStyle('bottom', '9px')
    absoluteMarker.setStyle('backgroundColor', '#0000ff')
    absoluteHost.add(absoluteMarker)
}
