export default function createNestedMarginsLayout({ ui, rendererName }) {
    const stage = ui.create()
    stage.style('flex', '1')
    stage.style('flexDirection', 'row')
    stage.style('padding', '40px')
    stage.style('gap', '32px')
    ui.root.add(stage)

    const stack = ui.create()
    stack.style('width', '260px')
    stack.style('height', '220px')
    stack.style('flexDirection', 'column')
    stack.style('padding', '16px')
    stack.style('borderTopWidth', '2px')
    stack.style('borderLeftWidth', '2px')
    stack.style('borderRightWidth', '2px')
    stack.style('borderBottomWidth', '2px')
    stack.style('borderTopStyle', 'solid')
    stack.style('borderLeftStyle', 'solid')
    stack.style('borderRightStyle', 'solid')
    stack.style('borderBottomStyle', 'solid')
    stack.style('borderTopColor', '#464')
    stack.style('borderLeftColor', '#464')
    stack.style('borderRightColor', '#464')
    stack.style('borderBottomColor', '#464')
    stack.style('backgroundColor', '#eef7ee')
    stage.add(stack)

    const stack_child_1 = ui.create()
    stack_child_1.style('width', '120px')
    stack_child_1.style('height', '34px')
    stack_child_1.style('backgroundColor', '#d3e7d3')

    stack.add(stack_child_1)

    const marginParent = ui.create()
    marginParent.style('width', '160px')
    marginParent.style('height', '120px')
    marginParent.style('marginTop', '17px')
    marginParent.style('marginLeft', '23px')
    marginParent.style('padding', '14px')
    marginParent.style('borderTopWidth', '2px')
    marginParent.style('borderLeftWidth', '2px')
    marginParent.style('borderRightWidth', '2px')
    marginParent.style('borderBottomWidth', '2px')
    marginParent.style('borderTopStyle', 'solid')
    marginParent.style('borderLeftStyle', 'solid')
    marginParent.style('borderRightStyle', 'solid')
    marginParent.style('borderBottomStyle', 'solid')
    marginParent.style('borderTopColor', '#595')
    marginParent.style('borderLeftColor', '#595')
    marginParent.style('borderRightColor', '#595')
    marginParent.style('borderBottomColor', '#595')
    marginParent.style('backgroundColor', '#dff0df')
    stack.add(marginParent)

    const marginChild = ui.create()
    marginChild.style('width', '96px')
    marginChild.style('height', '64px')
    marginChild.style('marginTop', '11px')
    marginChild.style('marginLeft', '9px')
    marginChild.style('padding', '8px')
    marginChild.style('borderTopWidth', '2px')
    marginChild.style('borderLeftWidth', '2px')
    marginChild.style('borderRightWidth', '2px')
    marginChild.style('borderBottomWidth', '2px')
    marginChild.style('borderTopStyle', 'solid')
    marginChild.style('borderLeftStyle', 'solid')
    marginChild.style('borderRightStyle', 'solid')
    marginChild.style('borderBottomStyle', 'solid')
    marginChild.style('borderTopColor', '#696')
    marginChild.style('borderLeftColor', '#696')
    marginChild.style('borderRightColor', '#696')
    marginChild.style('borderBottomColor', '#696')
    marginChild.style('backgroundColor', '#c9e6c9')
    marginParent.add(marginChild)

    const nestedMarginMarker = ui.create()
    nestedMarginMarker.style('width', '18px')
    nestedMarginMarker.style('height', '18px')
    nestedMarginMarker.style('backgroundColor', '#008800')
    marginChild.add(nestedMarginMarker)

    const rowHost = ui.create()
    rowHost.style('width', '300px')
    rowHost.style('height', '120px')
    rowHost.style('flexDirection', 'row')
    rowHost.style('alignItems', 'flex-start')
    rowHost.style('padding', '12px')
    rowHost.style('borderTopWidth', '2px')
    rowHost.style('borderLeftWidth', '2px')
    rowHost.style('borderRightWidth', '2px')
    rowHost.style('borderBottomWidth', '2px')
    rowHost.style('borderTopStyle', 'solid')
    rowHost.style('borderLeftStyle', 'solid')
    rowHost.style('borderRightStyle', 'solid')
    rowHost.style('borderBottomStyle', 'solid')
    rowHost.style('borderTopColor', '#745')
    rowHost.style('borderLeftColor', '#745')
    rowHost.style('borderRightColor', '#745')
    rowHost.style('borderBottomColor', '#745')
    rowHost.style('backgroundColor', '#f8edf2')
    stage.add(rowHost)

    const rowHost_child_2 = ui.create()
    rowHost_child_2.style('width', '56px')
    rowHost_child_2.style('height', '40px')
    rowHost_child_2.style('marginTop', '15px')
    rowHost_child_2.style('marginLeft', '19px')
    rowHost_child_2.style('marginRight', '27px')
    rowHost_child_2.style('backgroundColor', '#ebccd8')

    rowHost.add(rowHost_child_2)

    const afterMarginMarker = ui.create()
    afterMarginMarker.style('width', '22px')
    afterMarginMarker.style('height', '22px')
    afterMarginMarker.style('marginTop', '21px')
    afterMarginMarker.style('backgroundColor', '#cc3366')
    rowHost.add(afterMarginMarker)

    const endAlignedMarginHost = ui.create()
    endAlignedMarginHost.style('width', '90px')
    endAlignedMarginHost.style('height', '150px')
    endAlignedMarginHost.style('flexDirection', 'column')
    endAlignedMarginHost.style('justifyContent', 'flex-end')
    endAlignedMarginHost.style('alignItems', 'flex-end')
    endAlignedMarginHost.style('padding', '12px')
    endAlignedMarginHost.style('borderTopWidth', '2px')
    endAlignedMarginHost.style('borderLeftWidth', '2px')
    endAlignedMarginHost.style('borderRightWidth', '2px')
    endAlignedMarginHost.style('borderBottomWidth', '2px')
    endAlignedMarginHost.style('borderTopStyle', 'solid')
    endAlignedMarginHost.style('borderLeftStyle', 'solid')
    endAlignedMarginHost.style('borderRightStyle', 'solid')
    endAlignedMarginHost.style('borderBottomStyle', 'solid')
    endAlignedMarginHost.style('borderTopColor', '#764')
    endAlignedMarginHost.style('borderLeftColor', '#764')
    endAlignedMarginHost.style('borderRightColor', '#764')
    endAlignedMarginHost.style('borderBottomColor', '#764')
    endAlignedMarginHost.style('backgroundColor', '#fff0df')
    stage.add(endAlignedMarginHost)

    const endAlignedMarginHost_child_3 = ui.create()
    endAlignedMarginHost_child_3.style('width', '52px')
    endAlignedMarginHost_child_3.style('height', '30px')
    endAlignedMarginHost_child_3.style('backgroundColor', '#f3d2b0')

    endAlignedMarginHost.add(endAlignedMarginHost_child_3)

    const endAlignedMarginMarker = ui.create()
    endAlignedMarginMarker.style('width', '24px')
    endAlignedMarginMarker.style('height', '24px')
    endAlignedMarginMarker.style('marginTop', '13px')
    endAlignedMarginMarker.style('marginLeft', '17px')
    endAlignedMarginMarker.style('marginRight', '19px')
    endAlignedMarginMarker.style('backgroundColor', '#dd7700')
    endAlignedMarginHost.add(endAlignedMarginMarker)
}
