export default function createNestedPercentDimensionsLayout({ ui, rendererName }) {
    const stage = ui.create()
    stage.style('flex', '1')
    stage.style('padding', '40px')
    ui.root.add(stage)

    const frame = ui.create()
    frame.style('width', '360px')
    frame.style('height', '260px')
    frame.style('position', 'relative')
    frame.style('flexDirection', 'row')
    frame.style('alignItems', 'flex-start')
    frame.style('padding', '20px')
    frame.style('borderTopWidth', '4px')
    frame.style('borderLeftWidth', '4px')
    frame.style('borderRightWidth', '4px')
    frame.style('borderBottomWidth', '4px')
    frame.style('borderTopStyle', 'solid')
    frame.style('borderLeftStyle', 'solid')
    frame.style('borderRightStyle', 'solid')
    frame.style('borderBottomStyle', 'solid')
    frame.style('borderTopColor', '#345')
    frame.style('borderLeftColor', '#345')
    frame.style('borderRightColor', '#345')
    frame.style('borderBottomColor', '#345')
    frame.style('gap', '16px')
    frame.style('backgroundColor', '#eef1f8')
    stage.add(frame)

    const percentHost = ui.create()
    percentHost.style('width', '60%')
    percentHost.style('height', '70%')
    percentHost.style('flexDirection', 'column')
    percentHost.style('padding', '12px')
    percentHost.style('borderTopWidth', '2px')
    percentHost.style('borderLeftWidth', '2px')
    percentHost.style('borderRightWidth', '2px')
    percentHost.style('borderBottomWidth', '2px')
    percentHost.style('borderTopStyle', 'solid')
    percentHost.style('borderLeftStyle', 'solid')
    percentHost.style('borderRightStyle', 'solid')
    percentHost.style('borderBottomStyle', 'solid')
    percentHost.style('borderTopColor', '#467')
    percentHost.style('borderLeftColor', '#467')
    percentHost.style('borderRightColor', '#467')
    percentHost.style('borderBottomColor', '#467')
    percentHost.style('backgroundColor', '#d9e7ff')
    frame.add(percentHost)

    const percentSizeMarker = ui.create()
    percentSizeMarker.style('width', '50%')
    percentSizeMarker.style('height', '40%')
    percentSizeMarker.style('backgroundColor', '#1166dd')
    percentHost.add(percentSizeMarker)

    const endAlignedPercentHost = ui.create()
    endAlignedPercentHost.style('width', '80%')
    endAlignedPercentHost.style('height', '50%')
    endAlignedPercentHost.style('flexDirection', 'column')
    endAlignedPercentHost.style('justifyContent', 'flex-end')
    endAlignedPercentHost.style('alignItems', 'flex-end')
    endAlignedPercentHost.style('padding', '8px')
    endAlignedPercentHost.style('borderTopWidth', '2px')
    endAlignedPercentHost.style('borderLeftWidth', '2px')
    endAlignedPercentHost.style('borderRightWidth', '2px')
    endAlignedPercentHost.style('borderBottomWidth', '2px')
    endAlignedPercentHost.style('borderTopStyle', 'solid')
    endAlignedPercentHost.style('borderLeftStyle', 'solid')
    endAlignedPercentHost.style('borderRightStyle', 'solid')
    endAlignedPercentHost.style('borderBottomStyle', 'solid')
    endAlignedPercentHost.style('borderTopColor', '#358')
    endAlignedPercentHost.style('borderLeftColor', '#358')
    endAlignedPercentHost.style('borderRightColor', '#358')
    endAlignedPercentHost.style('borderBottomColor', '#358')
    endAlignedPercentHost.style('backgroundColor', '#c8dcff')
    percentHost.add(endAlignedPercentHost)

    const endAlignedPercentMarker = ui.create()
    endAlignedPercentMarker.style('width', '35%')
    endAlignedPercentMarker.style('height', '30%')
    endAlignedPercentMarker.style('backgroundColor', '#003c99')
    endAlignedPercentHost.add(endAlignedPercentMarker)

    const absoluteHost = ui.create()
    absoluteHost.style('width', '120px')
    absoluteHost.style('height', '140px')
    absoluteHost.style('position', 'relative')
    absoluteHost.style('padding', '10px')
    absoluteHost.style('borderTopWidth', '2px')
    absoluteHost.style('borderLeftWidth', '2px')
    absoluteHost.style('borderRightWidth', '2px')
    absoluteHost.style('borderBottomWidth', '2px')
    absoluteHost.style('borderTopStyle', 'solid')
    absoluteHost.style('borderLeftStyle', 'solid')
    absoluteHost.style('borderRightStyle', 'solid')
    absoluteHost.style('borderBottomStyle', 'solid')
    absoluteHost.style('borderTopColor', '#975')
    absoluteHost.style('borderLeftColor', '#975')
    absoluteHost.style('borderRightColor', '#975')
    absoluteHost.style('borderBottomColor', '#975')
    absoluteHost.style('backgroundColor', '#fde9d5')
    frame.add(absoluteHost)

    const percentOffsetMarker = ui.create()
    percentOffsetMarker.style('width', '30px')
    percentOffsetMarker.style('height', '24px')
    percentOffsetMarker.style('position', 'absolute')
    percentOffsetMarker.style('left', '25%')
    percentOffsetMarker.style('top', '20%')
    percentOffsetMarker.style('backgroundColor', '#ff6b00')
    absoluteHost.add(percentOffsetMarker)
}
