export default function createDeepNestedPaintLayout({ ui, rendererName }) {
    //

    const shell = ui.create()
    shell.style('flex', '1')
    shell.style('flexDirection', 'column')
    shell.style('padding', '24px')
    shell.style('borderTopWidth', '3px')
    shell.style('borderLeftWidth', '3px')
    shell.style('borderRightWidth', '3px')
    shell.style('borderBottomWidth', '3px')
    shell.style('borderTopStyle', 'solid')
    shell.style('borderLeftStyle', 'solid')
    shell.style('borderRightStyle', 'solid')
    shell.style('borderBottomStyle', 'solid')
    shell.style('borderTopColor', '#222')
    shell.style('borderLeftColor', '#222')
    shell.style('borderRightColor', '#222')
    shell.style('borderBottomColor', '#222')
    shell.style('gap', '12px')
    shell.style('backgroundColor', '#f4f4f4')
    ui.root.add(shell)

    const header = ui.create()
    header.style('height', '44px')
    header.style('backgroundColor', '#d8e8ff')
    shell.add(header)

    const row = ui.create()
    row.style('height', '420px')
    row.style('flexDirection', 'row')
    row.style('padding', '13px')
    row.style('borderTopWidth', '2px')
    row.style('borderLeftWidth', '2px')
    row.style('borderRightWidth', '2px')
    row.style('borderBottomWidth', '2px')
    row.style('borderTopStyle', 'solid')
    row.style('borderLeftStyle', 'solid')
    row.style('borderRightStyle', 'solid')
    row.style('borderBottomStyle', 'solid')
    row.style('borderTopColor', '#446')
    row.style('borderLeftColor', '#446')
    row.style('borderRightColor', '#446')
    row.style('borderBottomColor', '#446')
    row.style('gap', '17px')
    row.style('alignItems', 'center')
    row.style('backgroundColor', '#eef5ee')
    shell.add(row)

    const row_child_1 = ui.create()
    row_child_1.style('width', '92px')
    row_child_1.style('height', '146px')
    row_child_1.style('backgroundColor', '#f0d8d8')

    row.add(row_child_1)

    const shiftedColumn = ui.create()
    shiftedColumn.style('flex', '1')
    shiftedColumn.style('height', '320px')
    shiftedColumn.style('position', 'relative')
    shiftedColumn.style('left', '11px')
    shiftedColumn.style('top', '7px')
    shiftedColumn.style('flexDirection', 'column')
    shiftedColumn.style('justifyContent', 'center')
    shiftedColumn.style('alignItems', 'flex-end')
    shiftedColumn.style('padding', '19px')
    shiftedColumn.style('borderTopWidth', '4px')
    shiftedColumn.style('borderLeftWidth', '4px')
    shiftedColumn.style('borderRightWidth', '4px')
    shiftedColumn.style('borderBottomWidth', '4px')
    shiftedColumn.style('borderTopStyle', 'solid')
    shiftedColumn.style('borderLeftStyle', 'solid')
    shiftedColumn.style('borderRightStyle', 'solid')
    shiftedColumn.style('borderBottomStyle', 'solid')
    shiftedColumn.style('borderTopColor', '#484')
    shiftedColumn.style('borderLeftColor', '#484')
    shiftedColumn.style('borderRightColor', '#484')
    shiftedColumn.style('borderBottomColor', '#484')
    shiftedColumn.style('gap', '15px')
    shiftedColumn.style('backgroundColor', '#fff8df')
    row.add(shiftedColumn)

    const shiftedColumn_child_2 = ui.create()
    shiftedColumn_child_2.style('width', '88px')
    shiftedColumn_child_2.style('height', '36px')
    shiftedColumn_child_2.style('backgroundColor', '#dfdfdf')

    shiftedColumn.add(shiftedColumn_child_2)

    const nestedRow = ui.create()
    nestedRow.style('width', '468px')
    nestedRow.style('height', '190px')
    nestedRow.style('position', 'relative')
    nestedRow.style('flexDirection', 'row')
    nestedRow.style('justifyContent', 'space-between')
    nestedRow.style('alignItems', 'center')
    nestedRow.style('padding', '11px')
    nestedRow.style('borderTopWidth', '3px')
    nestedRow.style('borderLeftWidth', '3px')
    nestedRow.style('borderRightWidth', '3px')
    nestedRow.style('borderBottomWidth', '3px')
    nestedRow.style('borderTopStyle', 'solid')
    nestedRow.style('borderLeftStyle', 'solid')
    nestedRow.style('borderRightStyle', 'solid')
    nestedRow.style('borderBottomStyle', 'solid')
    nestedRow.style('borderTopColor', '#884')
    nestedRow.style('borderLeftColor', '#884')
    nestedRow.style('borderRightColor', '#884')
    nestedRow.style('borderBottomColor', '#884')
    nestedRow.style('gap', '9px')
    nestedRow.style('backgroundColor', '#f8eaff')
    shiftedColumn.add(nestedRow)

    const flowStack = ui.create()
    flowStack.style('width', '124px')
    flowStack.style('height', '132px')
    flowStack.style('flexDirection', 'column')
    flowStack.style('justifyContent', 'flex-end')
    flowStack.style('alignItems', 'flex-start')
    flowStack.style('padding', '7px')
    flowStack.style('borderTopWidth', '2px')
    flowStack.style('borderLeftWidth', '2px')
    flowStack.style('borderRightWidth', '2px')
    flowStack.style('borderBottomWidth', '2px')
    flowStack.style('borderTopStyle', 'solid')
    flowStack.style('borderLeftStyle', 'solid')
    flowStack.style('borderRightStyle', 'solid')
    flowStack.style('borderBottomStyle', 'solid')
    flowStack.style('borderTopColor', '#855')
    flowStack.style('borderLeftColor', '#855')
    flowStack.style('borderRightColor', '#855')
    flowStack.style('borderBottomColor', '#855')
    flowStack.style('gap', '6px')
    flowStack.style('backgroundColor', '#ffe8e8')
    nestedRow.add(flowStack)

    const flowStack_child_3 = ui.create()
    flowStack_child_3.style('width', '42px')
    flowStack_child_3.style('height', '28px')
    flowStack_child_3.style('backgroundColor', '#f2caca')

    flowStack.add(flowStack_child_3)

    const flowMarker = ui.create()
    flowMarker.style('width', '20px')
    flowMarker.style('height', '20px')
    flowMarker.style('backgroundColor', '#ff0000')
    flowStack.add(flowMarker)

    const alignedHost = ui.create()
    alignedHost.style('width', '148px')
    alignedHost.style('height', '132px')
    alignedHost.style('flexDirection', 'row')
    alignedHost.style('justifyContent', 'center')
    alignedHost.style('alignItems', 'flex-end')
    alignedHost.style('padding', '8px')
    alignedHost.style('borderTopWidth', '2px')
    alignedHost.style('borderLeftWidth', '2px')
    alignedHost.style('borderRightWidth', '2px')
    alignedHost.style('borderBottomWidth', '2px')
    alignedHost.style('borderTopStyle', 'solid')
    alignedHost.style('borderLeftStyle', 'solid')
    alignedHost.style('borderRightStyle', 'solid')
    alignedHost.style('borderBottomStyle', 'solid')
    alignedHost.style('borderTopColor', '#585')
    alignedHost.style('borderLeftColor', '#585')
    alignedHost.style('borderRightColor', '#585')
    alignedHost.style('borderBottomColor', '#585')
    alignedHost.style('backgroundColor', '#eaffea')
    nestedRow.add(alignedHost)

    const alignedMarker = ui.create()
    alignedMarker.style('width', '24px')
    alignedMarker.style('height', '18px')
    alignedMarker.style('backgroundColor', '#00aa00')
    alignedHost.add(alignedMarker)

    const absoluteHost = ui.create()
    absoluteHost.style('width', '138px')
    absoluteHost.style('height', '132px')
    absoluteHost.style('position', 'relative')
    absoluteHost.style('flexDirection', 'column')
    absoluteHost.style('padding', '10px')
    absoluteHost.style('borderTopWidth', '2px')
    absoluteHost.style('borderLeftWidth', '2px')
    absoluteHost.style('borderRightWidth', '2px')
    absoluteHost.style('borderBottomWidth', '2px')
    absoluteHost.style('borderTopStyle', 'solid')
    absoluteHost.style('borderLeftStyle', 'solid')
    absoluteHost.style('borderRightStyle', 'solid')
    absoluteHost.style('borderBottomStyle', 'solid')
    absoluteHost.style('borderTopColor', '#558')
    absoluteHost.style('borderLeftColor', '#558')
    absoluteHost.style('borderRightColor', '#558')
    absoluteHost.style('borderBottomColor', '#558')
    absoluteHost.style('backgroundColor', '#e8eaff')
    nestedRow.add(absoluteHost)

    const absoluteHost_child_4 = ui.create()
    absoluteHost_child_4.style('width', '52px')
    absoluteHost_child_4.style('height', '34px')
    absoluteHost_child_4.style('backgroundColor', '#cacaf2')

    absoluteHost.add(absoluteHost_child_4)

    const absoluteMarker = ui.create()
    absoluteMarker.style('width', '22px')
    absoluteMarker.style('height', '22px')
    absoluteMarker.style('position', 'absolute')
    absoluteMarker.style('right', '13px')
    absoluteMarker.style('bottom', '9px')
    absoluteMarker.style('backgroundColor', '#0000ff')
    absoluteHost.add(absoluteMarker)
}
