import { loadImage, loadJson } from '../../../src/utils/load-assets'

export default async function createUnitsClampLayout({ ui }) {
    const poppins_image = await loadImage('/assets/fonts/Poppins-Regular.mtsdf.png')
    const poppins_json = await loadJson('/assets/fonts/Poppins-Regular.mtsdf.json')
    const img = await loadImage('/assets/texture.jpg')

    ui.fontRegister('Poppins-Regular', poppins_image, poppins_json)
    ui.imageUpload(img.src, img)

    const stage = ui.create()
    stage.style('width', 'clamp(36rem, 72vw, 60rem)')
    stage.style('height', 'clamp(28rem, 76vh, 44rem)')
    stage.style('minWidth', 'clamp(32rem, 60vw, 52rem)')
    stage.style('minHeight', 'clamp(24rem, 60vh, 36rem)')
    stage.style('maxWidth', 'clamp(40rem, 80vw, 64rem)')
    stage.style('maxHeight', 'clamp(32rem, 82vh, 48rem)')
    stage.style('padding', 'clamp(1rem, 2vh, 2rem) clamp(1rem, 2vw, 2rem)')
    stage.style('paddingTop', 'clamp(1rem, 2vh, 2rem)')
    stage.style('paddingRight', 'clamp(1rem, 2vw, 2rem)')
    stage.style('paddingBottom', 'clamp(1rem, 2vh, 2rem)')
    stage.style('paddingLeft', 'clamp(1rem, 2vw, 2rem)')
    stage.style('margin', 'clamp(1rem, 2vh, 2rem) clamp(1rem, 2vw, 2rem)')
    stage.style('marginTop', 'clamp(1rem, 2vh, 2rem)')
    stage.style('marginRight', 'clamp(1rem, 2vw, 2rem)')
    stage.style('marginBottom', 'clamp(1rem, 2vh, 2rem)')
    stage.style('marginLeft', 'clamp(1rem, 2vw, 2rem)')
    stage.style('gap', 'clamp(0.75rem, 2vh, 1.5rem)')
    stage.style('rowGap', 'clamp(0.75rem, 2vh, 1.5rem)')
    stage.style('columnGap', 'clamp(0.75rem, 2vw, 1.5rem)')
    stage.style('flexDirection', 'column')
    stage.style('justifyContent', 'center')
    stage.style('backgroundColor', '#18202b')
    ui.root.add(stage)

    const title = ui.create()
    title.style('fontFamily', 'Poppins-Regular')
    title.style('fontSize', 'clamp(1.5rem, 2.5vw, 2.5rem)')
    title.style('lineHeight', 'clamp(2rem, 5vh, 3rem)')
    title.style('letterSpacing', 'clamp(0.025rem, 0.1vw, 0.1rem)')
    title.style('color', '#f8fafc')
    title.text('Responsive clamp layout')
    stage.add(title)

    const card = ui.create()
    card.style('width', 'clamp(28rem, 60vw, 52rem)')
    card.style('minWidth', 'clamp(24rem, 50vw, 44rem)')
    card.style('minHeight', 'clamp(14rem, 36vh, 24rem)')
    card.style('maxWidth', 'clamp(32rem, 64vw, 56rem)')
    card.style('maxHeight', 'clamp(20rem, 50vh, 32rem)')
    card.style('flex', '0 1 clamp(18rem, 44vh, 28rem)')
    card.style('flexBasis', 'clamp(18rem, 44vh, 28rem)')
    card.style('padding', 'clamp(0.75rem, 2vh, 1.5rem) clamp(0.75rem, 2vw, 1.5rem)')
    card.style('gap', 'clamp(0.5rem, 1.5vh, 1rem)')
    card.style('flexDirection', 'column')
    card.style('backgroundColor', '#2563eb')
    card.style('border', 'clamp(2px, 0.25vw, 4px) solid #93c5fd')
    card.style('borderTopWidth', 'clamp(2px, 0.25vw, 4px)')
    card.style('borderRightWidth', 'clamp(2px, 0.25vw, 4px)')
    card.style('borderBottomWidth', 'clamp(2px, 0.25vw, 4px)')
    card.style('borderLeftWidth', 'clamp(2px, 0.25vw, 4px)')
    card.style('borderRadius', 'clamp(0.75rem, 1.25vw, 1.5rem) clamp(0.75rem, 2vh, 1.5rem)')
    card.style('borderTopLeftRadius', 'clamp(0.75rem, 1.25vw, 1.5rem)')
    card.style('borderTopRightRadius', 'clamp(0.75rem, 2vh, 1.5rem)')
    card.style('borderBottomRightRadius', 'clamp(0.75rem, 1.25vw, 1.5rem)')
    card.style('borderBottomLeftRadius', 'clamp(0.75rem, 2vh, 1.5rem)')
    stage.add(card)

    const card_title = ui.create()
    card_title.style('fontFamily', 'Poppins-Regular')
    card_title.style('fontSize', 'clamp(1rem, 1.6vw, 1.5rem)')
    card_title.style('lineHeight', 'clamp(1.5rem, 3.5vh, 2rem)')
    card_title.style('color', '#ffffff')
    card_title.text('Every value stays between responsive limits')
    card.add(card_title)

    const body = ui.create()
    body.style('width', 'clamp(24rem, 52vw, 46rem)')
    body.style('padding', 'clamp(0.5rem, 1vh, 1rem) clamp(0.5rem, 1vw, 1rem)')
    body.style('fontFamily', 'Poppins-Regular')
    body.style('fontSize', 'clamp(0.875rem, 1.4vw, 1.25rem)')
    body.style('lineHeight', 'clamp(1.25rem, 3vh, 1.75rem)')
    body.style('letterSpacing', 'clamp(0.02rem, 0.05vw, 0.075rem)')
    body.style('color', '#172554')
    body.style('backgroundColor', '#dbeafe')
    body.text('Resize the viewport: fluid values grow until they reach their minimum or maximum.')
    card.add(body)

    const clamp_features = ui.create()
    clamp_features.style('width', 'clamp(24rem, 52vw, 46rem)')
    clamp_features.style('height', 'clamp(5rem, 12vh, 8rem)')
    clamp_features.style('columnGap', 'clamp(0.75rem, 2vw, 1.5rem)')
    clamp_features.style('flexDirection', 'row')
    card.add(clamp_features)

    const image = ui.create()
    image.style('width', 'clamp(8rem, 18vw, 15rem)')
    image.style('height', 'clamp(5rem, 12vh, 8rem)')
    image.style('flex', '0 1 clamp(8rem, 18vw, 15rem)')
    image.style('flexBasis', 'clamp(8rem, 18vw, 15rem)')
    image.style('backgroundColor', '#bfdbfe')
    image.style('backgroundImage', img.src)
    image.style('backgroundSize', 'clamp(7rem, 16vw, 13rem) clamp(4rem, 9vh, 7rem)')
    image.style('backgroundPosition', 'clamp(0.25rem, 1vw, 1rem) clamp(0.25rem, 1.5vh, 1rem)')
    clamp_features.add(image)

    const offsets = ui.create()
    offsets.style('width', 'clamp(14rem, 30vw, 27rem)')
    offsets.style('height', 'clamp(5rem, 12vh, 8rem)')
    offsets.style('columnGap', 'clamp(0.5rem, 2vw, 1.25rem)')
    offsets.style('flexDirection', 'row')
    offsets.style('alignItems', 'center')
    clamp_features.add(offsets)

    for (const [offset, value] of [
        ['top', 'clamp(0.125rem, 0.5vh, 0.5rem)'],
        ['right', 'clamp(0.125rem, 0.5vw, 0.5rem)'],
        ['bottom', 'clamp(0.125rem, 0.5vh, 0.5rem)'],
        ['left', 'clamp(0.125rem, 0.5vw, 0.5rem)'],
    ]) {
        const square = ui.create()
        square.style('width', 'clamp(2rem, 4vw, 3.5rem)')
        square.style('height', 'clamp(2rem, 6vh, 3.5rem)')
        square.style('position', 'relative')
        square.style(offset, value)
        square.style('backgroundColor', '#f8fafc')
        square.style('borderRadius', 'clamp(0.25rem, 0.75vw, 0.75rem)')
        offsets.add(square)
    }
}
