export default function createWrappedPercentRelativeOffsetsLayout({
    ui,
    rendererName,
}) {
    const stage = ui.create()
    stage.setStyle('flex', '1')
    stage.setStyle('flexDirection', 'row')
    stage.setStyle('padding', '40px')
    stage.setStyle('gap', '16px')
    ui.root.add(stage)

    const rowTop = ui.create()
    rowTop.setStyle('width', '120px')
    rowTop.setStyle('height', '120px')
    rowTop.setStyle('flexDirection', 'row')
    rowTop.setStyle('flexWrap', 'wrap')
    rowTop.setStyle('alignContent', 'flex-start')
    rowTop.setStyle('padding', '8px')
    rowTop.setStyle('gap', '6px')
    rowTop.setStyle('backgroundColor', '#eef5ee')
    stage.add(rowTop)

    const rowTop_child_1 = ui.create()
    rowTop_child_1.setStyle('width', '70px')
    rowTop_child_1.setStyle('height', '34px')
    rowTop_child_1.setStyle('backgroundColor', '#cde8cd')

    rowTop.add(rowTop_child_1)

    const rowTopRelative = ui.create()
    rowTopRelative.setStyle('width', '70px')
    rowTopRelative.setStyle('height', '34px')
    rowTopRelative.setStyle('position', 'relative')
    rowTopRelative.setStyle('top', '10%')
    rowTopRelative.setStyle('backgroundColor', '#00aa00')
    rowTop.add(rowTopRelative)

    const rowBottom = ui.create()
    rowBottom.setStyle('width', '120px')
    rowBottom.setStyle('height', '120px')
    rowBottom.setStyle('flexDirection', 'row')
    rowBottom.setStyle('flexWrap', 'wrap')
    rowBottom.setStyle('alignContent', 'flex-start')
    rowBottom.setStyle('padding', '8px')
    rowBottom.setStyle('gap', '6px')
    rowBottom.setStyle('backgroundColor', '#f5eeee')
    stage.add(rowBottom)

    const rowBottom_child_2 = ui.create()
    rowBottom_child_2.setStyle('width', '70px')
    rowBottom_child_2.setStyle('height', '34px')
    rowBottom_child_2.setStyle('backgroundColor', '#e8cdcd')

    rowBottom.add(rowBottom_child_2)

    const rowBottomRelative = ui.create()
    rowBottomRelative.setStyle('width', '70px')
    rowBottomRelative.setStyle('height', '34px')
    rowBottomRelative.setStyle('position', 'relative')
    rowBottomRelative.setStyle('bottom', '10%')
    rowBottomRelative.setStyle('backgroundColor', '#cc3300')
    rowBottom.add(rowBottomRelative)

    const rowReverseTop = ui.create()
    rowReverseTop.setStyle('width', '120px')
    rowReverseTop.setStyle('height', '120px')
    rowReverseTop.setStyle('flexDirection', 'row-reverse')
    rowReverseTop.setStyle('flexWrap', 'wrap')
    rowReverseTop.setStyle('alignContent', 'flex-start')
    rowReverseTop.setStyle('padding', '8px')
    rowReverseTop.setStyle('gap', '6px')
    rowReverseTop.setStyle('backgroundColor', '#f2eaff')
    stage.add(rowReverseTop)

    const rowReverseTop_child_3 = ui.create()
    rowReverseTop_child_3.setStyle('width', '70px')
    rowReverseTop_child_3.setStyle('height', '34px')
    rowReverseTop_child_3.setStyle('backgroundColor', '#decfff')

    rowReverseTop.add(rowReverseTop_child_3)

    const rowReverseTopRelative = ui.create()
    rowReverseTopRelative.setStyle('width', '70px')
    rowReverseTopRelative.setStyle('height', '34px')
    rowReverseTopRelative.setStyle('position', 'relative')
    rowReverseTopRelative.setStyle('top', '10%')
    rowReverseTopRelative.setStyle('backgroundColor', '#aa00ff')
    rowReverseTop.add(rowReverseTopRelative)

    const rowReverseBottom = ui.create()
    rowReverseBottom.setStyle('width', '120px')
    rowReverseBottom.setStyle('height', '120px')
    rowReverseBottom.setStyle('flexDirection', 'row-reverse')
    rowReverseBottom.setStyle('flexWrap', 'wrap')
    rowReverseBottom.setStyle('alignContent', 'flex-start')
    rowReverseBottom.setStyle('padding', '8px')
    rowReverseBottom.setStyle('gap', '6px')
    rowReverseBottom.setStyle('backgroundColor', '#fff0df')
    stage.add(rowReverseBottom)

    const rowReverseBottom_child_4 = ui.create()
    rowReverseBottom_child_4.setStyle('width', '70px')
    rowReverseBottom_child_4.setStyle('height', '34px')
    rowReverseBottom_child_4.setStyle('backgroundColor', '#f3d2b0')

    rowReverseBottom.add(rowReverseBottom_child_4)

    const rowReverseBottomRelative = ui.create()
    rowReverseBottomRelative.setStyle('width', '70px')
    rowReverseBottomRelative.setStyle('height', '34px')
    rowReverseBottomRelative.setStyle('position', 'relative')
    rowReverseBottomRelative.setStyle('bottom', '10%')
    rowReverseBottomRelative.setStyle('backgroundColor', '#dd7700')
    rowReverseBottom.add(rowReverseBottomRelative)
}
