export default function createWrappedColumnRelativeOffsetsLayout({ ui, rendererName }) {
    const stage = ui.create()
    stage.style('flex', '1')
    stage.style('flexDirection', 'row')
    stage.style('padding', '40px')
    stage.style('gap', '16px')
    ui.root.add(stage)

    const columnLeft = ui.create()
    columnLeft.style('width', '120px')
    columnLeft.style('height', '120px')
    columnLeft.style('flexDirection', 'column')
    columnLeft.style('flexWrap', 'wrap')
    columnLeft.style('alignContent', 'flex-start')
    columnLeft.style('padding', '8px')
    columnLeft.style('gap', '6px')
    columnLeft.style('backgroundColor', '#eef5ee')
    stage.add(columnLeft)

    const columnLeft_child_1 = ui.create()
    columnLeft_child_1.style('width', '34px')
    columnLeft_child_1.style('height', '70px')
    columnLeft_child_1.style('backgroundColor', '#cde8cd')

    columnLeft.add(columnLeft_child_1)

    const columnLeftRelative = ui.create()
    columnLeftRelative.style('width', '34px')
    columnLeftRelative.style('height', '70px')
    columnLeftRelative.style('position', 'relative')
    columnLeftRelative.style('left', '11px')
    columnLeftRelative.style('backgroundColor', '#00aa00')
    columnLeft.add(columnLeftRelative)

    const columnRight = ui.create()
    columnRight.style('width', '120px')
    columnRight.style('height', '120px')
    columnRight.style('flexDirection', 'column')
    columnRight.style('flexWrap', 'wrap')
    columnRight.style('alignContent', 'flex-start')
    columnRight.style('padding', '8px')
    columnRight.style('gap', '6px')
    columnRight.style('backgroundColor', '#f5eeee')
    stage.add(columnRight)

    const columnRight_child_2 = ui.create()
    columnRight_child_2.style('width', '34px')
    columnRight_child_2.style('height', '70px')
    columnRight_child_2.style('backgroundColor', '#e8cdcd')

    columnRight.add(columnRight_child_2)

    const columnRightRelative = ui.create()
    columnRightRelative.style('width', '34px')
    columnRightRelative.style('height', '70px')
    columnRightRelative.style('position', 'relative')
    columnRightRelative.style('right', '9px')
    columnRightRelative.style('backgroundColor', '#cc3300')
    columnRight.add(columnRightRelative)

    const columnReverseLeft = ui.create()
    columnReverseLeft.style('width', '120px')
    columnReverseLeft.style('height', '120px')
    columnReverseLeft.style('flexDirection', 'column-reverse')
    columnReverseLeft.style('flexWrap', 'wrap')
    columnReverseLeft.style('alignContent', 'flex-start')
    columnReverseLeft.style('padding', '8px')
    columnReverseLeft.style('gap', '6px')
    columnReverseLeft.style('backgroundColor', '#f2eaff')
    stage.add(columnReverseLeft)

    const columnReverseLeft_child_3 = ui.create()
    columnReverseLeft_child_3.style('width', '34px')
    columnReverseLeft_child_3.style('height', '70px')
    columnReverseLeft_child_3.style('backgroundColor', '#decfff')

    columnReverseLeft.add(columnReverseLeft_child_3)

    const columnReverseLeftRelative = ui.create()
    columnReverseLeftRelative.style('width', '34px')
    columnReverseLeftRelative.style('height', '70px')
    columnReverseLeftRelative.style('position', 'relative')
    columnReverseLeftRelative.style('left', '11px')
    columnReverseLeftRelative.style('backgroundColor', '#aa00ff')
    columnReverseLeft.add(columnReverseLeftRelative)

    const columnReverseRight = ui.create()
    columnReverseRight.style('width', '120px')
    columnReverseRight.style('height', '120px')
    columnReverseRight.style('flexDirection', 'column-reverse')
    columnReverseRight.style('flexWrap', 'wrap')
    columnReverseRight.style('alignContent', 'flex-start')
    columnReverseRight.style('padding', '8px')
    columnReverseRight.style('gap', '6px')
    columnReverseRight.style('backgroundColor', '#fff0df')
    stage.add(columnReverseRight)

    const columnReverseRight_child_4 = ui.create()
    columnReverseRight_child_4.style('width', '34px')
    columnReverseRight_child_4.style('height', '70px')
    columnReverseRight_child_4.style('backgroundColor', '#f3d2b0')

    columnReverseRight.add(columnReverseRight_child_4)

    const columnReverseRightRelative = ui.create()
    columnReverseRightRelative.style('width', '34px')
    columnReverseRightRelative.style('height', '70px')
    columnReverseRightRelative.style('position', 'relative')
    columnReverseRightRelative.style('right', '9px')
    columnReverseRightRelative.style('backgroundColor', '#dd7700')
    columnReverseRight.add(columnReverseRightRelative)
}
