export default function createWrappedRelativeOffsetsLayout({ ui, rendererName }) {
    const stage = ui.create()
    stage.style('flex', '1')
    stage.style('flexDirection', 'row')
    stage.style('padding', '40px')
    stage.style('gap', '16px')
    ui.root.add(stage)

    const rowWrapTop = ui.create()
    rowWrapTop.style('width', '120px')
    rowWrapTop.style('height', '120px')
    rowWrapTop.style('flexDirection', 'row')
    rowWrapTop.style('flexWrap', 'wrap')
    rowWrapTop.style('alignContent', 'flex-start')
    rowWrapTop.style('padding', '8px')
    rowWrapTop.style('gap', '6px')
    rowWrapTop.style('backgroundColor', '#eef5ee')
    stage.add(rowWrapTop)

    const rowWrapTop_child_1 = ui.create()
    rowWrapTop_child_1.style('width', '70px')
    rowWrapTop_child_1.style('height', '34px')
    rowWrapTop_child_1.style('backgroundColor', '#cde8cd')

    rowWrapTop.add(rowWrapTop_child_1)

    const rowWrapTopRelative = ui.create()
    rowWrapTopRelative.style('width', '70px')
    rowWrapTopRelative.style('height', '34px')
    rowWrapTopRelative.style('position', 'relative')
    rowWrapTopRelative.style('top', '11px')
    rowWrapTopRelative.style('backgroundColor', '#00aa00')
    rowWrapTop.add(rowWrapTopRelative)

    const rowWrapBottom = ui.create()
    rowWrapBottom.style('width', '120px')
    rowWrapBottom.style('height', '120px')
    rowWrapBottom.style('flexDirection', 'row')
    rowWrapBottom.style('flexWrap', 'wrap')
    rowWrapBottom.style('alignContent', 'flex-start')
    rowWrapBottom.style('padding', '8px')
    rowWrapBottom.style('gap', '6px')
    rowWrapBottom.style('backgroundColor', '#f5eeee')
    stage.add(rowWrapBottom)

    const rowWrapBottom_child_2 = ui.create()
    rowWrapBottom_child_2.style('width', '70px')
    rowWrapBottom_child_2.style('height', '34px')
    rowWrapBottom_child_2.style('backgroundColor', '#e8cdcd')

    rowWrapBottom.add(rowWrapBottom_child_2)

    const rowWrapBottomRelative = ui.create()
    rowWrapBottomRelative.style('width', '70px')
    rowWrapBottomRelative.style('height', '34px')
    rowWrapBottomRelative.style('position', 'relative')
    rowWrapBottomRelative.style('bottom', '9px')
    rowWrapBottomRelative.style('backgroundColor', '#cc3300')
    rowWrapBottom.add(rowWrapBottomRelative)

    const rowNowrap = ui.create()
    rowNowrap.style('width', '144px')
    rowNowrap.style('height', '70px')
    rowNowrap.style('flexDirection', 'row')
    rowNowrap.style('flexWrap', 'nowrap')
    rowNowrap.style('padding', '8px')
    rowNowrap.style('gap', '6px')
    rowNowrap.style('backgroundColor', '#eef1f8')
    stage.add(rowNowrap)

    const rowNowrap_child_3 = ui.create()
    rowNowrap_child_3.style('width', '50px')
    rowNowrap_child_3.style('height', '34px')
    rowNowrap_child_3.style('backgroundColor', '#d9e7ff')

    rowNowrap.add(rowNowrap_child_3)

    const rowNowrapRelative = ui.create()
    rowNowrapRelative.style('width', '50px')
    rowNowrapRelative.style('height', '34px')
    rowNowrapRelative.style('position', 'relative')
    rowNowrapRelative.style('top', '11px')
    rowNowrapRelative.style('backgroundColor', '#1166dd')
    rowNowrap.add(rowNowrapRelative)

    const columnWrap = ui.create()
    columnWrap.style('width', '120px')
    columnWrap.style('height', '110px')
    columnWrap.style('flexDirection', 'column')
    columnWrap.style('flexWrap', 'wrap')
    columnWrap.style('alignContent', 'flex-start')
    columnWrap.style('padding', '8px')
    columnWrap.style('gap', '6px')
    columnWrap.style('backgroundColor', '#fff0df')
    stage.add(columnWrap)

    const columnWrap_child_4 = ui.create()
    columnWrap_child_4.style('width', '34px')
    columnWrap_child_4.style('height', '64px')
    columnWrap_child_4.style('backgroundColor', '#f3d2b0')

    columnWrap.add(columnWrap_child_4)

    const columnWrapRelative = ui.create()
    columnWrapRelative.style('width', '34px')
    columnWrapRelative.style('height', '64px')
    columnWrapRelative.style('position', 'relative')
    columnWrapRelative.style('top', '11px')
    columnWrapRelative.style('backgroundColor', '#dd7700')
    columnWrap.add(columnWrapRelative)

    const rowReverseWrap = ui.create()
    rowReverseWrap.style('width', '120px')
    rowReverseWrap.style('height', '120px')
    rowReverseWrap.style('flexDirection', 'row-reverse')
    rowReverseWrap.style('flexWrap', 'wrap')
    rowReverseWrap.style('alignContent', 'flex-start')
    rowReverseWrap.style('padding', '8px')
    rowReverseWrap.style('gap', '6px')
    rowReverseWrap.style('backgroundColor', '#f2eaff')
    stage.add(rowReverseWrap)

    const rowReverseWrap_child_5 = ui.create()
    rowReverseWrap_child_5.style('width', '70px')
    rowReverseWrap_child_5.style('height', '34px')
    rowReverseWrap_child_5.style('backgroundColor', '#decfff')

    rowReverseWrap.add(rowReverseWrap_child_5)

    const rowReverseWrapRelative = ui.create()
    rowReverseWrapRelative.style('width', '70px')
    rowReverseWrapRelative.style('height', '34px')
    rowReverseWrapRelative.style('position', 'relative')
    rowReverseWrapRelative.style('top', '11px')
    rowReverseWrapRelative.style('backgroundColor', '#aa00ff')
    rowReverseWrap.add(rowReverseWrapRelative)
}
