export default function createDisplayLayout({ ui, rendererName }) {
    const container = ui.create()
    container.style('flex', '1')
    container.style('flexDirection', 'row')
    container.style('gap', '16px')
    container.style('padding', '32px')
    container.style('backgroundColor', '#f4f5f7')
    ui.root.add(container)

    const flex = ui.create()
    flex.style('width', '120px')
    flex.style('height', '120px')
    flex.style('display', 'flex')
    flex.style('padding', '16px')
    flex.style('backgroundColor', '#2f80ed')
    container.add(flex)
    const flex_child_1 = ui.create()
    flex_child_1.style('width', '48px')
    flex_child_1.style('height', '48px')
    flex_child_1.style('backgroundColor', '#56ccf2')

    flex.add(flex_child_1)

    const none = ui.create()
    none.style('width', '120px')
    none.style('height', '120px')
    none.style('display', 'none')
    none.style('backgroundColor', '#eb5757')
    container.add(none)
    const none_child_2 = ui.create()
    none_child_2.style('width', '48px')
    none_child_2.style('height', '48px')
    none_child_2.style('backgroundColor', '#fb6897')

    none.add(none_child_2)

    const contents = ui.create()
    contents.style('width', '120px')
    contents.style('height', '120px')
    contents.style('display', 'contents')
    contents.style('padding', '16px')
    contents.style('backgroundColor', '#27ae60')
    container.add(contents)
    const contents_child_3 = ui.create()
    contents_child_3.style('width', '48px')
    contents_child_3.style('height', '48px')
    contents_child_3.style('backgroundColor', '#6fcf97')

    contents.add(contents_child_3)
}
