export default function createWrappedAlignContentRelativeOffsetsLayout({ ui, rendererName }) {
    const stage = ui.create()
    stage.style('flex', '1')
    stage.style('flexDirection', 'row')
    stage.style('padding', '40px')
    stage.style('gap', '16px')
    ui.root.add(stage)

    const centerTop = ui.create()
    centerTop.style('width', '120px')
    centerTop.style('height', '170px')
    centerTop.style('flexDirection', 'row')
    centerTop.style('flexWrap', 'wrap')
    centerTop.style('alignContent', 'center')
    centerTop.style('padding', '8px')
    centerTop.style('gap', '6px')
    centerTop.style('backgroundColor', '#eef5ee')
    stage.add(centerTop)

    const centerTopBase = ui.create()
    centerTopBase.style('width', '70px')
    centerTopBase.style('height', '34px')
    centerTopBase.style('backgroundColor', '#cde8cd')
    centerTop.add(centerTopBase)

    const centerTopRelative = ui.create()
    centerTopRelative.style('width', '70px')
    centerTopRelative.style('height', '34px')
    centerTopRelative.style('position', 'relative')
    centerTopRelative.style('top', '11px')
    centerTopRelative.style('backgroundColor', '#00aa00')
    centerTop.add(centerTopRelative)

    const centerBottom = ui.create()
    centerBottom.style('width', '120px')
    centerBottom.style('height', '170px')
    centerBottom.style('flexDirection', 'row')
    centerBottom.style('flexWrap', 'wrap')
    centerBottom.style('alignContent', 'center')
    centerBottom.style('padding', '8px')
    centerBottom.style('gap', '6px')
    centerBottom.style('backgroundColor', '#f5eeee')
    stage.add(centerBottom)

    const centerBottomBase = ui.create()
    centerBottomBase.style('width', '70px')
    centerBottomBase.style('height', '34px')
    centerBottomBase.style('backgroundColor', '#e8cdcd')
    centerBottom.add(centerBottomBase)

    const centerBottomRelative = ui.create()
    centerBottomRelative.style('width', '70px')
    centerBottomRelative.style('height', '34px')
    centerBottomRelative.style('position', 'relative')
    centerBottomRelative.style('bottom', '9px')
    centerBottomRelative.style('backgroundColor', '#cc3300')
    centerBottom.add(centerBottomRelative)

    const flexEndTop = ui.create()
    flexEndTop.style('width', '120px')
    flexEndTop.style('height', '170px')
    flexEndTop.style('flexDirection', 'row')
    flexEndTop.style('flexWrap', 'wrap')
    flexEndTop.style('alignContent', 'flex-end')
    flexEndTop.style('padding', '8px')
    flexEndTop.style('gap', '6px')
    flexEndTop.style('backgroundColor', '#f2eaff')
    stage.add(flexEndTop)

    const flexEndTopBase = ui.create()
    flexEndTopBase.style('width', '70px')
    flexEndTopBase.style('height', '34px')
    flexEndTopBase.style('backgroundColor', '#decfff')
    flexEndTop.add(flexEndTopBase)

    const flexEndTopRelative = ui.create()
    flexEndTopRelative.style('width', '70px')
    flexEndTopRelative.style('height', '34px')
    flexEndTopRelative.style('position', 'relative')
    flexEndTopRelative.style('top', '11px')
    flexEndTopRelative.style('backgroundColor', '#aa00ff')
    flexEndTop.add(flexEndTopRelative)

    const flexEndBottom = ui.create()
    flexEndBottom.style('width', '120px')
    flexEndBottom.style('height', '170px')
    flexEndBottom.style('flexDirection', 'row')
    flexEndBottom.style('flexWrap', 'wrap')
    flexEndBottom.style('alignContent', 'flex-end')
    flexEndBottom.style('padding', '8px')
    flexEndBottom.style('gap', '6px')
    flexEndBottom.style('backgroundColor', '#fff0df')
    stage.add(flexEndBottom)

    const flexEndBottomBase = ui.create()
    flexEndBottomBase.style('width', '70px')
    flexEndBottomBase.style('height', '34px')
    flexEndBottomBase.style('backgroundColor', '#f3d2b0')
    flexEndBottom.add(flexEndBottomBase)

    const flexEndBottomRelative = ui.create()
    flexEndBottomRelative.style('width', '70px')
    flexEndBottomRelative.style('height', '34px')
    flexEndBottomRelative.style('position', 'relative')
    flexEndBottomRelative.style('bottom', '9px')
    flexEndBottomRelative.style('backgroundColor', '#dd7700')
    flexEndBottom.add(flexEndBottomRelative)
}
