export default function createWrappedPercentRelativeOffsetsLayout({ ui, rendererName }) {
    const stage = ui.create()
    stage.style('flex', '1')
    stage.style('flexDirection', 'row')
    stage.style('padding', '40px')
    stage.style('gap', '16px')
    ui.root.add(stage)

    const rowTop = ui.create()
    rowTop.style('width', '120px')
    rowTop.style('height', '120px')
    rowTop.style('flexDirection', 'row')
    rowTop.style('flexWrap', 'wrap')
    rowTop.style('alignContent', 'flex-start')
    rowTop.style('padding', '8px')
    rowTop.style('gap', '6px')
    rowTop.style('backgroundColor', '#eef5ee')
    stage.add(rowTop)

    const rowTop_child_1 = ui.create()
    rowTop_child_1.style('width', '70px')
    rowTop_child_1.style('height', '34px')
    rowTop_child_1.style('backgroundColor', '#cde8cd')

    rowTop.add(rowTop_child_1)

    const rowTopRelative = ui.create()
    rowTopRelative.style('width', '70px')
    rowTopRelative.style('height', '34px')
    rowTopRelative.style('position', 'relative')
    rowTopRelative.style('top', '10%')
    rowTopRelative.style('backgroundColor', '#00aa00')
    rowTop.add(rowTopRelative)

    const rowBottom = ui.create()
    rowBottom.style('width', '120px')
    rowBottom.style('height', '120px')
    rowBottom.style('flexDirection', 'row')
    rowBottom.style('flexWrap', 'wrap')
    rowBottom.style('alignContent', 'flex-start')
    rowBottom.style('padding', '8px')
    rowBottom.style('gap', '6px')
    rowBottom.style('backgroundColor', '#f5eeee')
    stage.add(rowBottom)

    const rowBottom_child_2 = ui.create()
    rowBottom_child_2.style('width', '70px')
    rowBottom_child_2.style('height', '34px')
    rowBottom_child_2.style('backgroundColor', '#e8cdcd')

    rowBottom.add(rowBottom_child_2)

    const rowBottomRelative = ui.create()
    rowBottomRelative.style('width', '70px')
    rowBottomRelative.style('height', '34px')
    rowBottomRelative.style('position', 'relative')
    rowBottomRelative.style('bottom', '10%')
    rowBottomRelative.style('backgroundColor', '#cc3300')
    rowBottom.add(rowBottomRelative)

    const rowReverseTop = ui.create()
    rowReverseTop.style('width', '120px')
    rowReverseTop.style('height', '120px')
    rowReverseTop.style('flexDirection', 'row-reverse')
    rowReverseTop.style('flexWrap', 'wrap')
    rowReverseTop.style('alignContent', 'flex-start')
    rowReverseTop.style('padding', '8px')
    rowReverseTop.style('gap', '6px')
    rowReverseTop.style('backgroundColor', '#f2eaff')
    stage.add(rowReverseTop)

    const rowReverseTop_child_3 = ui.create()
    rowReverseTop_child_3.style('width', '70px')
    rowReverseTop_child_3.style('height', '34px')
    rowReverseTop_child_3.style('backgroundColor', '#decfff')

    rowReverseTop.add(rowReverseTop_child_3)

    const rowReverseTopRelative = ui.create()
    rowReverseTopRelative.style('width', '70px')
    rowReverseTopRelative.style('height', '34px')
    rowReverseTopRelative.style('position', 'relative')
    rowReverseTopRelative.style('top', '10%')
    rowReverseTopRelative.style('backgroundColor', '#aa00ff')
    rowReverseTop.add(rowReverseTopRelative)

    const rowReverseBottom = ui.create()
    rowReverseBottom.style('width', '120px')
    rowReverseBottom.style('height', '120px')
    rowReverseBottom.style('flexDirection', 'row-reverse')
    rowReverseBottom.style('flexWrap', 'wrap')
    rowReverseBottom.style('alignContent', 'flex-start')
    rowReverseBottom.style('padding', '8px')
    rowReverseBottom.style('gap', '6px')
    rowReverseBottom.style('backgroundColor', '#fff0df')
    stage.add(rowReverseBottom)

    const rowReverseBottom_child_4 = ui.create()
    rowReverseBottom_child_4.style('width', '70px')
    rowReverseBottom_child_4.style('height', '34px')
    rowReverseBottom_child_4.style('backgroundColor', '#f3d2b0')

    rowReverseBottom.add(rowReverseBottom_child_4)

    const rowReverseBottomRelative = ui.create()
    rowReverseBottomRelative.style('width', '70px')
    rowReverseBottomRelative.style('height', '34px')
    rowReverseBottomRelative.style('position', 'relative')
    rowReverseBottomRelative.style('bottom', '10%')
    rowReverseBottomRelative.style('backgroundColor', '#dd7700')
    rowReverseBottom.add(rowReverseBottomRelative)
}
