export default function createWrappedMainAxisRelativeOffsetsLayout({ ui, rendererName }) {
    const stage = ui.create()
    stage.style('flex', '1')
    stage.style('flexDirection', 'row')
    stage.style('padding', '40px')
    stage.style('gap', '16px')
    ui.root.add(stage)

    const rowLeft = ui.create()
    rowLeft.style('width', '120px')
    rowLeft.style('height', '120px')
    rowLeft.style('flexDirection', 'row')
    rowLeft.style('flexWrap', 'wrap')
    rowLeft.style('alignContent', 'flex-start')
    rowLeft.style('padding', '8px')
    rowLeft.style('gap', '6px')
    rowLeft.style('backgroundColor', '#eef5ee')
    stage.add(rowLeft)

    const rowLeft_child_1 = ui.create()
    rowLeft_child_1.style('width', '70px')
    rowLeft_child_1.style('height', '34px')
    rowLeft_child_1.style('backgroundColor', '#cde8cd')

    rowLeft.add(rowLeft_child_1)

    const rowLeftRelative = ui.create()
    rowLeftRelative.style('width', '70px')
    rowLeftRelative.style('height', '34px')
    rowLeftRelative.style('position', 'relative')
    rowLeftRelative.style('left', '11px')
    rowLeftRelative.style('backgroundColor', '#00aa00')
    rowLeft.add(rowLeftRelative)

    const rowReverseRight = ui.create()
    rowReverseRight.style('width', '120px')
    rowReverseRight.style('height', '120px')
    rowReverseRight.style('flexDirection', 'row-reverse')
    rowReverseRight.style('flexWrap', 'wrap')
    rowReverseRight.style('alignContent', 'flex-start')
    rowReverseRight.style('padding', '8px')
    rowReverseRight.style('gap', '6px')
    rowReverseRight.style('backgroundColor', '#f5eeee')
    stage.add(rowReverseRight)

    const rowReverseRight_child_2 = ui.create()
    rowReverseRight_child_2.style('width', '70px')
    rowReverseRight_child_2.style('height', '34px')
    rowReverseRight_child_2.style('backgroundColor', '#e8cdcd')

    rowReverseRight.add(rowReverseRight_child_2)

    const rowReverseRightRelative = ui.create()
    rowReverseRightRelative.style('width', '70px')
    rowReverseRightRelative.style('height', '34px')
    rowReverseRightRelative.style('position', 'relative')
    rowReverseRightRelative.style('right', '9px')
    rowReverseRightRelative.style('backgroundColor', '#cc3300')
    rowReverseRight.add(rowReverseRightRelative)

    const rowRight = ui.create()
    rowRight.style('width', '120px')
    rowRight.style('height', '120px')
    rowRight.style('flexDirection', 'row')
    rowRight.style('flexWrap', 'wrap')
    rowRight.style('alignContent', 'flex-start')
    rowRight.style('padding', '8px')
    rowRight.style('gap', '6px')
    rowRight.style('backgroundColor', '#eef1f8')
    stage.add(rowRight)

    const rowRight_child_3 = ui.create()
    rowRight_child_3.style('width', '70px')
    rowRight_child_3.style('height', '34px')
    rowRight_child_3.style('backgroundColor', '#d9e7ff')

    rowRight.add(rowRight_child_3)

    const rowRightRelative = ui.create()
    rowRightRelative.style('width', '70px')
    rowRightRelative.style('height', '34px')
    rowRightRelative.style('position', 'relative')
    rowRightRelative.style('right', '9px')
    rowRightRelative.style('backgroundColor', '#1166dd')
    rowRight.add(rowRightRelative)

    const rowReverseLeft = ui.create()
    rowReverseLeft.style('width', '120px')
    rowReverseLeft.style('height', '120px')
    rowReverseLeft.style('flexDirection', 'row-reverse')
    rowReverseLeft.style('flexWrap', 'wrap')
    rowReverseLeft.style('alignContent', 'flex-start')
    rowReverseLeft.style('padding', '8px')
    rowReverseLeft.style('gap', '6px')
    rowReverseLeft.style('backgroundColor', '#fff0df')
    stage.add(rowReverseLeft)

    const rowReverseLeft_child_4 = ui.create()
    rowReverseLeft_child_4.style('width', '70px')
    rowReverseLeft_child_4.style('height', '34px')
    rowReverseLeft_child_4.style('backgroundColor', '#f3d2b0')

    rowReverseLeft.add(rowReverseLeft_child_4)

    const rowReverseLeftRelative = ui.create()
    rowReverseLeftRelative.style('width', '70px')
    rowReverseLeftRelative.style('height', '34px')
    rowReverseLeftRelative.style('position', 'relative')
    rowReverseLeftRelative.style('left', '11px')
    rowReverseLeftRelative.style('backgroundColor', '#dd7700')
    rowReverseLeft.add(rowReverseLeftRelative)

    const columnTop = ui.create()
    columnTop.style('width', '120px')
    columnTop.style('height', '120px')
    columnTop.style('flexDirection', 'column')
    columnTop.style('flexWrap', 'wrap')
    columnTop.style('alignContent', 'flex-start')
    columnTop.style('padding', '8px')
    columnTop.style('gap', '6px')
    columnTop.style('backgroundColor', '#f2eaff')
    stage.add(columnTop)

    const columnTop_child_5 = ui.create()
    columnTop_child_5.style('width', '34px')
    columnTop_child_5.style('height', '70px')
    columnTop_child_5.style('backgroundColor', '#decfff')

    columnTop.add(columnTop_child_5)

    const columnTopRelative = ui.create()
    columnTopRelative.style('width', '34px')
    columnTopRelative.style('height', '70px')
    columnTopRelative.style('position', 'relative')
    columnTopRelative.style('top', '11px')
    columnTopRelative.style('backgroundColor', '#aa00ff')
    columnTop.add(columnTopRelative)

    const columnBottom = ui.create()
    columnBottom.style('width', '120px')
    columnBottom.style('height', '120px')
    columnBottom.style('flexDirection', 'column')
    columnBottom.style('flexWrap', 'wrap')
    columnBottom.style('alignContent', 'flex-start')
    columnBottom.style('padding', '8px')
    columnBottom.style('gap', '6px')
    columnBottom.style('backgroundColor', '#eaf7f7')
    stage.add(columnBottom)

    const columnBottom_child_6 = ui.create()
    columnBottom_child_6.style('width', '34px')
    columnBottom_child_6.style('height', '70px')
    columnBottom_child_6.style('backgroundColor', '#c7e6e6')

    columnBottom.add(columnBottom_child_6)

    const columnBottomRelative = ui.create()
    columnBottomRelative.style('width', '34px')
    columnBottomRelative.style('height', '70px')
    columnBottomRelative.style('position', 'relative')
    columnBottomRelative.style('bottom', '9px')
    columnBottomRelative.style('backgroundColor', '#008888')
    columnBottom.add(columnBottomRelative)

    const columnReverseBottom = ui.create()
    columnReverseBottom.style('width', '120px')
    columnReverseBottom.style('height', '120px')
    columnReverseBottom.style('flexDirection', 'column-reverse')
    columnReverseBottom.style('flexWrap', 'wrap')
    columnReverseBottom.style('alignContent', 'flex-start')
    columnReverseBottom.style('padding', '8px')
    columnReverseBottom.style('gap', '6px')
    columnReverseBottom.style('backgroundColor', '#fff0df')
    stage.add(columnReverseBottom)

    const columnReverseBottom_child_7 = ui.create()
    columnReverseBottom_child_7.style('width', '34px')
    columnReverseBottom_child_7.style('height', '70px')
    columnReverseBottom_child_7.style('backgroundColor', '#f3d2b0')

    columnReverseBottom.add(columnReverseBottom_child_7)

    const columnReverseBottomRelative = ui.create()
    columnReverseBottomRelative.style('width', '34px')
    columnReverseBottomRelative.style('height', '70px')
    columnReverseBottomRelative.style('position', 'relative')
    columnReverseBottomRelative.style('bottom', '9px')
    columnReverseBottomRelative.style('backgroundColor', '#dd7700')
    columnReverseBottom.add(columnReverseBottomRelative)

    const columnReverseTop = ui.create()
    columnReverseTop.style('width', '120px')
    columnReverseTop.style('height', '120px')
    columnReverseTop.style('flexDirection', 'column-reverse')
    columnReverseTop.style('flexWrap', 'wrap')
    columnReverseTop.style('alignContent', 'flex-start')
    columnReverseTop.style('padding', '8px')
    columnReverseTop.style('gap', '6px')
    columnReverseTop.style('backgroundColor', '#fff5e8')
    stage.add(columnReverseTop)

    const columnReverseTop_child_8 = ui.create()
    columnReverseTop_child_8.style('width', '34px')
    columnReverseTop_child_8.style('height', '70px')
    columnReverseTop_child_8.style('backgroundColor', '#f7d9b8')

    columnReverseTop.add(columnReverseTop_child_8)

    const columnReverseTopRelative = ui.create()
    columnReverseTopRelative.style('width', '34px')
    columnReverseTopRelative.style('height', '70px')
    columnReverseTopRelative.style('position', 'relative')
    columnReverseTopRelative.style('top', '11px')
    columnReverseTopRelative.style('backgroundColor', '#bb6600')
    columnReverseTop.add(columnReverseTopRelative)
}
