export default function createNestedRelativeOffsetsLayout({ ui, rendererName }) {
    const stage = ui.create()
    stage.style('flex', '1')
    stage.style('flexDirection', 'row')
    stage.style('padding', '40px')
    stage.style('gap', '32px')
    ui.root.add(stage)

    const positiveParent = ui.create()
    positiveParent.style('width', '220px')
    positiveParent.style('height', '220px')
    positiveParent.style('position', 'relative')
    positiveParent.style('left', '24px')
    positiveParent.style('top', '18px')
    positiveParent.style('padding', '20px')
    positiveParent.style('backgroundColor', '#ddeeff')
    stage.add(positiveParent)

    const positiveChild = ui.create()
    positiveChild.style('width', '150px')
    positiveChild.style('height', '150px')
    positiveChild.style('position', 'relative')
    positiveChild.style('left', '13px')
    positiveChild.style('top', '9px')
    positiveChild.style('padding', '16px')
    positiveChild.style('backgroundColor', '#bbddff')
    positiveParent.add(positiveChild)

    const positiveGrandchild = ui.create()
    positiveGrandchild.style('width', '72px')
    positiveGrandchild.style('height', '72px')
    positiveGrandchild.style('position', 'relative')
    positiveGrandchild.style('left', '8px')
    positiveGrandchild.style('top', '6px')
    positiveGrandchild.style('backgroundColor', '#99ccff')
    positiveChild.add(positiveGrandchild)

    const positiveMarker = ui.create()
    positiveMarker.style('width', '20px')
    positiveMarker.style('height', '20px')
    positiveMarker.style('backgroundColor', '#0066ff')
    positiveGrandchild.add(positiveMarker)

    const mixedParent = ui.create()
    mixedParent.style('width', '220px')
    mixedParent.style('height', '220px')
    mixedParent.style('position', 'relative')
    mixedParent.style('left', '-18px')
    mixedParent.style('top', '-11px')
    mixedParent.style('padding', '20px')
    mixedParent.style('backgroundColor', '#ffe8dd')
    stage.add(mixedParent)

    const mixedChild = ui.create()
    mixedChild.style('width', '150px')
    mixedChild.style('height', '150px')
    mixedChild.style('position', 'relative')
    mixedChild.style('right', '-12px')
    mixedChild.style('bottom', '10px')
    mixedChild.style('padding', '16px')
    mixedChild.style('backgroundColor', '#ffc9aa')
    mixedParent.add(mixedChild)

    const mixedGrandchild = ui.create()
    mixedGrandchild.style('width', '72px')
    mixedGrandchild.style('height', '72px')
    mixedGrandchild.style('position', 'relative')
    mixedGrandchild.style('left', '-7px')
    mixedGrandchild.style('bottom', '-5px')
    mixedGrandchild.style('backgroundColor', '#ffaa77')
    mixedChild.add(mixedGrandchild)

    const mixedMarker = ui.create()
    mixedMarker.style('width', '20px')
    mixedMarker.style('height', '20px')
    mixedMarker.style('backgroundColor', '#ff5500')
    mixedGrandchild.add(mixedMarker)
}
