import { loadImage, loadJson } from '../../shared/load-assets'

export default async function createUnitsViewportLayout({ ui, resources, registerFont }) {
    const poppins_image = await loadImage('examples/assets/fonts/Poppins-Regular.mtsdf.png')
    const poppins_json = await loadJson('examples/assets/fonts/Poppins-Regular.mtsdf.json')
    const img = await loadImage('examples/assets/images/texture.jpg')

    registerFont('Poppins-Regular', poppins_image, poppins_json)
    resources.registerImage?.(img.src, img)

    const stage = ui.create()
    stage.style('width', '72vw')
    stage.style('height', '76vh')
    stage.style('minWidth', '60vw')
    stage.style('minHeight', '60vh')
    stage.style('maxWidth', '80vw')
    stage.style('maxHeight', '82vh')
    stage.style('padding', '2vh 2vw')
    stage.style('paddingTop', '2vh')
    stage.style('paddingRight', '2vw')
    stage.style('paddingBottom', '2vh')
    stage.style('paddingLeft', '2vw')
    stage.style('margin', '2vh 2vw')
    stage.style('marginTop', '2vh')
    stage.style('marginRight', '2vw')
    stage.style('marginBottom', '2vh')
    stage.style('marginLeft', '2vw')
    stage.style('gap', '2vh')
    stage.style('rowGap', '2vh')
    stage.style('columnGap', '2vw')
    stage.style('flexDirection', 'column')
    stage.style('justifyContent', 'center')
    stage.style('backgroundColor', '#18202b')
    ui.root.add(stage)

    const title = ui.create()
    title.style('fontFamily', 'Poppins-Regular')
    title.style('fontSize', '2.5vw')
    title.style('lineHeight', '5vh')
    title.style('letterSpacing', '0.1vw')
    title.style('color', '#f8fafc')
    title.text('Responsive viewport layout')
    stage.add(title)

    const card = ui.create()
    card.style('width', '60vw')
    card.style('minWidth', '50vw')
    card.style('minHeight', '36vh')
    card.style('maxWidth', '64vw')
    card.style('maxHeight', '50vh')
    card.style('flex', '0 1 44vh')
    card.style('flexBasis', '44vh')
    card.style('padding', '2vh 2vw')
    card.style('gap', '1.5vh')
    card.style('flexDirection', 'column')
    card.style('backgroundColor', '#2563eb')
    card.style('border', '0.25vw solid #93c5fd')
    card.style('borderTopWidth', '0.25vw')
    card.style('borderRightWidth', '0.25vw')
    card.style('borderBottomWidth', '0.25vw')
    card.style('borderLeftWidth', '0.25vw')
    card.style('borderRadius', '1.25vw 2vh')
    card.style('borderTopLeftRadius', '1.25vw')
    card.style('borderTopRightRadius', '2vh')
    card.style('borderBottomRightRadius', '1.25vw')
    card.style('borderBottomLeftRadius', '2vh')
    stage.add(card)

    const card_title = ui.create()
    card_title.style('fontFamily', 'Poppins-Regular')
    card_title.style('fontSize', '1.6vw')
    card_title.style('lineHeight', '3.5vh')
    card_title.style('color', '#ffffff')
    card_title.text('Everything scales from the viewport')
    card.add(card_title)

    const body = ui.create()
    body.style('width', '52vw')
    body.style('padding', '1vh 1vw')
    body.style('fontFamily', 'Poppins-Regular')
    body.style('fontSize', '1.4vw')
    body.style('lineHeight', '3vh')
    body.style('letterSpacing', '0.05vw')
    body.style('color', '#172554')
    body.style('backgroundColor', '#dbeafe')
    body.text('Resize the browser viewport and the layout and text will adapt together.')
    card.add(body)

    const viewport_features = ui.create()
    viewport_features.style('width', '52vw')
    viewport_features.style('height', '12vh')
    viewport_features.style('columnGap', '2vw')
    viewport_features.style('flexDirection', 'row')
    card.add(viewport_features)

    const image = ui.create()
    image.style('width', '18vw')
    image.style('height', '12vh')
    image.style('flex', '0 1 18vw')
    image.style('flexBasis', '18vw')
    image.style('backgroundColor', '#bfdbfe')
    image.style('backgroundImage', img.src)
    image.style('backgroundSize', '16vw 9vh')
    image.style('backgroundPosition', '1vw 1.5vh')
    viewport_features.add(image)

    const offsets = ui.create()
    offsets.style('width', '30vw')
    offsets.style('height', '12vh')
    offsets.style('columnGap', '2vw')
    offsets.style('flexDirection', 'row')
    offsets.style('alignItems', 'center')
    viewport_features.add(offsets)

    for (const [offset, value] of [
        ['top', '0.5vh'],
        ['right', '0.5vw'],
        ['bottom', '0.5vh'],
        ['left', '0.5vw'],
    ]) {
        const square = ui.create()
        square.style('width', '4vw')
        square.style('height', '6vh')
        square.style('position', 'relative')
        square.style(offset, value)
        square.style('backgroundColor', '#f8fafc')
        square.style('borderRadius', '0.75vw')
        offsets.add(square)
    }
}
