import { FONT_NAME_CHANGA } from '../../examples/shared/assets'
import Style from '../../src/style'

export const STYLE_VALUES: Record<string, string> = {
    zIndex: '2',
    overflow: 'hidden',
    overflowX: 'hidden',
    overflowY: 'hidden',
    opacity: '0.5',
    boxShadow: '1px 2px 3px 0px #123456',
    textShadow: '1px 2px 3px #123456',
    textStroke: '2px #123456',
    border: '2px solid #123456',
    borderRadius: '8px',
    borderTopLeftRadius: '8px',
    borderTopRightRadius: '8px',
    borderBottomLeftRadius: '8px',
    borderBottomRightRadius: '8px',
    borderTopStyle: 'solid',
    borderLeftStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderTopColor: '#123456',
    borderLeftColor: '#123456',
    borderRightColor: '#123456',
    borderBottomColor: '#123456',
    backgroundColor: '#123456',
    backgroundImage: '/examples/assets/images/coin.png',
    backgroundSize: '20px 30px',
    backgroundSizeWidth: '20px',
    backgroundSizeHeight: '30px',
    backgroundPosition: '20px 30px',
    backgroundPositionX: '20px',
    backgroundPositionY: '30px',
    backgroundRepeat: 'repeat-x',
    color: '#123456',
    fontFamily: FONT_NAME_CHANGA,
    fontSize: '24px',
    lineHeight: '30px',
    letterSpacing: '2px',
    textAlign: 'center',
    whiteSpace: 'nowrap',
    position: 'absolute',
    top: '10px',
    left: '10px',
    right: '10px',
    bottom: '10px',
    alignContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    flexDirection: 'column',
    flexWrap: 'wrap',
    justifyContent: 'center',
    margin: '10px',
    marginTop: '10px',
    marginLeft: '10px',
    marginRight: '10px',
    marginBottom: '10px',
    flex: '2 0 40px',
    flexGrow: '2',
    flexShrink: '0',
    flexBasis: '40px',
    width: '160px',
    height: '140px',
    minWidth: '180px',
    minHeight: '140px',
    maxWidth: '60px',
    maxHeight: '60px',
    boxSizing: 'content-box',
    aspectRatio: '2',
    borderTopWidth: '4px',
    borderLeftWidth: '4px',
    borderRightWidth: '4px',
    borderBottomWidth: '4px',
    display: 'none',
    pointerEvents: 'none',
    direction: 'rtl',
    padding: '10px',
    paddingTop: '10px',
    paddingLeft: '10px',
    paddingRight: '10px',
    paddingBottom: '10px',
    gap: '10px',
    rowGap: '10px',
    columnGap: '10px',
}

export const STYLE_NAMES = Object.values(Style.STYLE).map((style) => style.name)
export const STYLE_CASES = STYLE_NAMES.map((name) => ({
    name,
    value: STYLE_VALUES[name],
    expanded_names: Style.resolveStyle(name, 'unset').expanded.map((style) => style.name),
}))
